// ./backup/tools.ts

/* 
  用于开发环境工具列表获取
*/

import { ref } from "vue";
export const tools = ref([
  {
    catId: 1,
    category: "对话模型",
    id: 1,
    name: "豆包",
    url: "https://www.doubao.com/chat/",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/doubao.png",
    description: "精准答疑、提供灵感、辅助创作",
    score: 4.2,
    ratingCount: 350,
  },
  {
    catId: 1,
    category: "对话模型",
    id: 2,
    name: "deepseek",
    url: "https://chat.deepseek.com/",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/deepseek.png",
    description: "强大的混合专家（MoE）语言模型，训练和推理经济高效",
    score: 4.6,
    ratingCount: 420,
  },
  {
    catId: 1,
    category: "对话模型",
    id: 3,
    name: "文小言",
    url: "https://yiyan.baidu.com/",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/wxyy.png",
    description: "提供信息查询、知识科普及文案生成服务",
    score: 4.3,
    ratingCount: 500,
  },
  {
    catId: 1,
    category: "对话模型",
    id: 4,
    name: "通义千问",
    url: "https://tongyi.aliyun.com/",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/tyqw.png",
    description: "基于阿里云，语言处理能力强",
    score: 4.4,
    ratingCount: 380,
  },
  {
    catId: 1,
    category: "对话模型",
    id: 5,
    name: "Kimi",
    url: "https://kimi.moonshot.cn/",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/kimi.png",
    description: "对话服务专业贴心，覆盖多领域内容",
    score: 4.7,
    ratingCount: 600,
  },
  {
    catId: 1,
    category: "对话模型",
    id: 6,
    name: "智谱清言",
    url: "https://chatglm.cn/",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/zpqy.png",
    description: "语言模型先进，问答创作、多轮对话表现出色",
    score: 4.5,
    ratingCount: 450,
  },
  {
    catId: 2,
    category: "办公助手",
    id: 7,
    name: "AiPPT",
    url: "https://www.aippt.cn",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/AiPPT.png",
    description: "全自动生成PPT大纲、模板、Word-PPT……",
    score: 4.1,
    ratingCount: 280,
  },
  {
    catId: 2,
    category: "办公助手",
    id: 8,
    name: "iSlide",
    url: "https://www.islide.cc",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/iSlide.png",
    description: "AI一键设计PPT",
    score: 4.3,
    ratingCount: 320,
  },
  {
    catId: 2,
    category: "办公助手",
    id: 9,
    name: "WPS AI",
    url: "https://ai.wps.cn",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/wps-ai.png",
    description: "WPS的AI插件（智能PPT、表格、文档整理……）",
    score: 4.4,
    ratingCount: 360,
  },
  {
    catId: 2,
    category: "办公助手",
    id: 10,
    name: "ChatPPT",
    url: "http://www.chat-ppt.com",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/chatppt.png",
    description: "AI插件，支持Office、WPS，自动文档生成",
    score: 4.2,
    ratingCount: 290,
  },
  {
    catId: 2,
    category: "办公助手",
    id: 11,
    name: "酷表ChatExcel",
    url: "https://chatexcel.com",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/chat-excel.png",
    description: "智能Excel公式",
    score: 4.0,
    ratingCount: 250,
  },
  {
    catId: 2,
    category: "办公助手",
    id: 12,
    name: "商汤办公小浣熊",
    url: "https://raccoon.sensetime.com",
    logoUrl:
      "https://a1.x914.com/alight/i/AITeach/toolsLogo/xiaohuanxiong.png",
    description: "智能图表",
    score: 4.5,
    ratingCount: 300,
  },
  {
    catId: 3,
    category: "会议纪要",
    id: 13,
    name: "讯飞听见",
    url: "https://www.iflyrec.com",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/xftj.png",
    description: "音视频转文字，实时录音转文字，同传，翻译……",
    score: 4.3,
    ratingCount: 400,
  },
  {
    catId: 3,
    category: "会议纪要",
    id: 14,
    name: "阿里通义听悟",
    url: "https://tingwu.aliyun.com",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/tytw.png",
    description: "实时转录，音视频转文字，互联网内容提炼……",
    score: 4.4,
    ratingCount: 420,
  },
  {
    catId: 3,
    category: "会议纪要",
    id: 15,
    name: "飞书妙记",
    url: "https://www.feishu.cn/product/minutes?from=thosefree.com",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/fsmj.png",
    description: "飞书文档中的会议纪要工具，实时转录，音视频转文字",
    score: 4.2,
    ratingCount: 380,
  },
  {
    catId: 3,
    category: "会议纪要",
    id: 16,
    name: "腾讯会议AI",
    url: "https://meeting.tencent.com/ai/index.html",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/tc-meet-ai.png",
    description: "腾讯会议录制后会议纪要整理",
    score: 4.1,
    ratingCount: 300,
  },
  {
    catId: 4,
    category: "脑图生成",
    id: 17,
    name: "ProcessOn",
    url: "https://www.processon.com",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/ProcessOn.png",
    description: "AI思维导图",
    score: 4.3,
    ratingCount: 350,
  },
  {
    catId: 4,
    category: "脑图生成",
    id: 18,
    name: "亿图脑图",
    url: "https://www.edrawsoft.cn/mindmaster",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/ytnt.png",
    description: "AI思维导图",
    score: 4.4,
    ratingCount: 400,
  },
  {
    catId: 4,
    category: "脑图生成",
    id: 19,
    name: "GitMind思乎",
    url: "https://gitmind.cn/",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/gitmind.png",
    description: "AI思维导图",
    score: 4.2,
    ratingCount: 320,
  },
  {
    catId: 4,
    category: "脑图生成",
    id: 20,
    name: "boardmix 博思白板",
    url: "https://boardmix.cn/ai-whiteboard",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/boardmix.jpg",
    description:
      "实时协作的智慧白板上，一键生成PPT、用AI协助创作思维导图、AI绘画、AI写作，共享资源素材",
    score: 4.5,
    ratingCount: 380,
  },
  {
    catId: 4,
    category: "脑图生成",
    id: 21,
    name: "妙办画板",
    url: "https://imiaoban.com",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/mbhb.png",
    description: "生成流程图、思维导图",
    score: 4.3,
    ratingCount: 280,
  },
  {
    catId: 5,
    category: "写作辅助",
    id: 22,
    name: "腾讯Effidit",
    url: "https://effidit.qq.com",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/effidit.png",
    description:
      "智能纠错、文本补全、文本改写、文本扩写、词语推荐、句子推荐与生成等功能",
    score: 4.4,
    ratingCount: 450,
  },
  {
    catId: 5,
    category: "写作辅助",
    id: 23,
    name: "讯飞写作",
    url: "https://huixie.iflyrec.com",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/xfxz.png",
    description: "AI对话写作、模板写作、素材、润色……",
    score: 4.3,
    ratingCount: 500,
  },
  {
    catId: 5,
    category: "写作辅助",
    id: 24,
    name: "深言达意",
    url: "https://www.shenyandayi.com",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/sydy.png",
    description: "根据模糊描述，找词找句的智能写作工具",
    score: 4.2,
    ratingCount: 360,
  },
  {
    catId: 5,
    category: "写作辅助",
    id: 25,
    name: "阿里悉语",
    url: "https://login.taobao.com",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/alxy.png",
    description: "淘宝专用的商品文案生成，输入商品的淘宝链接即可获得文案",
    score: 4.1,
    ratingCount: 400,
  },
  {
    catId: 5,
    category: "写作辅助",
    id: 26,
    name: "字节火山写作",
    url: "https://www.writingo.net",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/zjhsxz.jpg",
    description: "全文润色的AI智能写作",
    score: 4.5,
    ratingCount: 320,
  },
  {
    catId: 5,
    category: "写作辅助",
    id: 27,
    name: "光速写作",
    url: "https://guangsuxie.com",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/gsxz.png",
    description: "作业帮旗下：全文生成、PPT生成、问答助手、写作助手",
    score: 4.3,
    ratingCount: 380,
  },
  {
    catId: 5,
    category: "写作辅助",
    id: 28,
    name: "WriteWise",
    url: "https://www.ximalaya.com/gatekeeper/write-wise-web?ref=ai-bot.cn",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/writewise.png",
    description: "喜马拉雅小说创作工具",
    score: 4.4,
    ratingCount: 420,
  },
  {
    catId: 5,
    category: "写作辅助",
    id: 29,
    name: "笔灵AI",
    url: "https://ibiling.cn",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/blAI.png",
    description: "一键生成工作计划、文案方案……",
    score: 4.2,
    ratingCount: 300,
  },
  {
    catId: 5,
    category: "写作辅助",
    id: 30,
    name: "易撰",
    url: "https://www.yizhuan5.com",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/yizhuan.png",
    description: "自媒体内容",
    score: 4.3,
    ratingCount: 350,
  },
  {
    catId: 5,
    category: "写作辅助",
    id: 31,
    name: "Giiso写作机器人",
    url: "https://www.giiso.com",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/Giiso.png",
    description: "写作、文配图、风格转换、文生图……",
    score: 4.4,
    ratingCount: 400,
  },
  {
    catId: 5,
    category: "写作辅助",
    id: 32,
    name: "5118 SEO优化精灵",
    url: "https://www.5118.com/seometa",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/5118-seo.png",
    description:
      "快速生成高质量SEO标题、Meta描述和关键字，轻松提升网站搜索引擎排名",
    score: 4.5,
    ratingCount: 450,
  },
  {
    catId: 6,
    category: "翻译工具",
    id: 33,
    name: "沉浸式翻译",
    url: "https://immersivetranslate.com",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/cjsfanyi.jpg",
    description: "翻译外语网页，PDF翻译，EPUB电子书翻译，视频双语字幕翻译等",
    score: 4.3,
    ratingCount: 300,
  },
  {
    catId: 6,
    category: "翻译工具",
    id: 34,
    name: "彩云小译",
    url: "https://fanyi.caiyunapp.com",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/caiyunxiaoyi.png",
    description: "多种格式文档的翻译、同声传译、文档翻译和网页翻译",
    score: 4.2,
    ratingCount: 350,
  },
  {
    catId: 6,
    category: "翻译工具",
    id: 35,
    name: "网易见外",
    url: "https://sight.youdao.com",
    logoUrl:
      "https://a1.x914.com/alight/i/AITeach/toolsLogo/wangyijianwai.png",
    description: "字幕、音频转写、同传、文档翻译……",
    score: 4.4,
    ratingCount: 400,
  },
  {
    catId: 7,
    category: "搜索引擎",
    id: 36,
    name: "天工AI搜索(昆仑万维)",
    url: "https://search.tiangong.cn",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/tiangong.png",
    description:
      "找资料、查信息、搜答案、搜文件，还会对海量搜索结果做AI智能聚合",
    score: 4.3,
    ratingCount: 380,
  },
  {
    catId: 7,
    category: "搜索引擎",
    id: 37,
    name: "360AI搜索",
    url: "https://ai.360.com",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/360AI.png",
    description: "AI搜索能够从海量的网站中主动寻找、提炼精准答案",
    score: 4.1,
    ratingCount: 320,
  },
  {
    catId: 7,
    category: "搜索引擎",
    id: 38,
    name: "秘塔AI搜索",
    url: "https://metaso.cn",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/mitaAI.png",
    description: "没有广告，直达结果",
    score: 4.5,
    ratingCount: 450,
  },
  {
    catId: 7,
    category: "搜索引擎",
    id: 39,
    name: "perplexity.ai",
    url: "www.perplexity.ai",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/perplexity.png",
    description: "黄仁勋带货的AI搜索引擎",
    score: 4.4,
    ratingCount: 500,
  },
  {
    catId: 7,
    category: "搜索引擎",
    id: 40,
    name: "sciphi.ai",
    url: "https://search.sciphi.ai",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/sciphi.jpg",
    description: "AI搜索引擎",
    score: 4.3,
    ratingCount: 360,
  },
  {
    catId: 7,
    category: "搜索引擎",
    id: 41,
    name: "devv.ai",
    url: "https://devv.ai",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/devv.png",
    description: "为开发人员打造的人工智能驱动的搜索引擎",
    score: 4.2,
    ratingCount: 280,
  },
  {
    catId: 8,
    category: "图像生成",
    id: 42,
    name: "通义万相",
    url: "https://tongyi.aliyun.com",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/tywanxiang.png",
    description: "AI生成图片，人工智能艺术创作大模型",
    score: 4.5,
    ratingCount: 420,
  },
  {
    catId: 8,
    category: "图像生成",
    id: 43,
    name: "文心一格",
    url: "https://yige.baidu.com",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/wxyg.png",
    description: "文生图像",
    score: 4.4,
    ratingCount: 380,
  },
  {
    catId: 8,
    category: "图像生成",
    id: 44,
    name: "剪映AI",
    url: "https://www.capcut.cn",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/jianyingAI.jpg",
    description: "剪映一键生成AI绘画",
    score: 4.3,
    ratingCount: 320,
  },
  {
    catId: 8,
    category: "图像生成",
    id: 45,
    name: "腾讯ARC",
    url: "https://arc.tencent.com",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/tencent-arc.png",
    description: "人像修复、人像抠图、动漫增强",
    score: 4.6,
    ratingCount: 400,
  },
  {
    catId: 8,
    category: "图像生成",
    id: 46,
    name: "360智绘",
    url: "https://ai.360.com",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/360zhihui.png",
    description: "风格化AI绘画、Lora训练",
    score: 4.2,
    ratingCount: 350,
  },
  {
    catId: 8,
    category: "图像生成",
    id: 47,
    name: "无限画",
    url: "https://588ku.com/ai/wuxianhua/Home",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/wuxianhua.png",
    description: "智能图像设计，整合千库网的设计行业知识经验、资源数据",
    score: 4.4,
    ratingCount: 380,
  },
  {
    catId: 8,
    category: "图像生成",
    id: 48,
    name: "美图设计室",
    url: "https://www.x-design.com",
    logoUrl:
      "https://a1.x914.com/alight/i/AITeach/toolsLogo/meitushejishi.webp",
    description: "图像智能处理，海报设计……",
    score: 4.3,
    ratingCount: 420,
  },
  {
    catId: 8,
    category: "图像生成",
    id: 49,
    name: "liblib.ai",
    url: "https://www.liblib.ai",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/liblib.png",
    description: "AI模型分享平台-各种风格的图像微调模型",
    score: 4.5,
    ratingCount: 300,
  },
  {
    catId: 8,
    category: "图像生成",
    id: 50,
    name: "Tusi.Art",
    url: "https://tusiart.com",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/Tusi-Art.webp",
    description: "AI模型分享平台",
    score: 4.4,
    ratingCount: 360,
  },
  {
    catId: 8,
    category: "图像生成",
    id: 51,
    name: "标小智Logo生成",
    url: "https://www.logosc.cn",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/biaoxiaozhi.jpg",
    description: "在线LOGO设计，生成企业VI",
    score: 4.3,
    ratingCount: 300,
  },
  {
    catId: 8,
    category: "图像生成",
    id: 52,
    name: "佐糖",
    url: "https://picwish.cn",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/zuotang.jpg",
    description: "丰富的图像处理工具",
    score: 4.2,
    ratingCount: 280,
  },
  {
    catId: 8,
    category: "图像生成",
    id: 53,
    name: "美图WHEE",
    url: "https://www.whee.com",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/whee.png",
    description: "文生图，图生图，文生视频，扩图改图超清……",
    score: 4.5,
    ratingCount: 350,
  },
  {
    catId: 8,
    category: "图像生成",
    id: 54,
    name: "无界AI",
    url: "https://www.wujieai.com",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/wujieAI.png",
    description: "文生图",
    score: 4.4,
    ratingCount: 400,
  },
  {
    catId: 8,
    category: "图像生成",
    id: 55,
    name: "BgSub",
    url: "https://bgsub.cn",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/BgSub.png",
    description: "抠图",
    score: 4.3,
    ratingCount: 250,
  },
  {
    catId: 8,
    category: "图像生成",
    id: 56,
    name: "阿里PicCopilot",
    url: "https://www.piccopilot.com",
    logoUrl:
      "https://a1.x914.com/alight/i/AITeach/toolsLogo/Ali-PicCopilot.png",
    description: "阿里巴巴国际，AI驱动图片优化工具，专门为电商领域提供服务",
    score: 4.5,
    ratingCount: 420,
  },
  {
    catId: 8,
    category: "图像生成",
    id: 57,
    name: "搜狐简单AI",
    url: "https://ai.sohu.com",
    logoUrl:
      "https://a1.x914.com/alight/i/AITeach/toolsLogo/souhujiandanAI.jpg",
    description: "智能图片生成平台和社区",
    score: 4.2,
    ratingCount: 300,
  },
  {
    catId: 9,
    category: "音频处理",
    id: 58,
    name: "度加创作工具",
    url: "https://aigc.baidu.com",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/dujia.jpg",
    description: "热搜一键成稿，文稿一键成片",
    score: 4.4,
    ratingCount: 380,
  },
  {
    catId: 9,
    category: "音频处理",
    id: 59,
    name: "魔音工坊",
    url: "https://www.moyin.com",
    logoUrl:
      "https://a1.x914.com/alight/i/AITeach/toolsLogo/moyingongfang.png",
    description: "AI配音工具",
    score: 4.3,
    ratingCount: 320,
  },
  {
    catId: 9,
    category: "音频处理",
    id: 60,
    name: "网易天音",
    url: "https://tianyin.music.163.com",
    logoUrl:
      "https://a1.x914.com/alight/i/AITeach/toolsLogo/wangyitianyin.png",
    description: "智能编曲，海量风格",
    score: 4.5,
    ratingCount: 400,
  },
  {
    catId: 9,
    category: "音频处理",
    id: 61,
    name: "TME Studio",
    url: "https://y.qq.com/tme_studio",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/TME-Studio.png",
    description: "腾讯音乐智能音乐生成工具",
    score: 4.4,
    ratingCount: 360,
  },
  {
    catId: 9,
    category: "音频处理",
    id: 62,
    name: "讯飞智作",
    url: "https://www.xfzhizuo.cn",
    logoUrl:
      "https://a1.x914.com/alight/i/AITeach/toolsLogo/xunfei-zhizuo.jpg",
    description: "配音、声音定制、虚拟主播、音视频处理……",
    score: 4.3,
    ratingCount: 300,
  },
  {
    catId: 10,
    category: "视频制作",
    id: 63,
    name: "PixVerse",
    url: "https://pixverse.ai",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/PixVerse.jpg",
    description: "文生视频",
    score: 4.5,
    ratingCount: 380,
  },
  {
    catId: 10,
    category: "视频制作",
    id: 64,
    name: "绘影字幕",
    url: "https://huiyingzimu.com",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/huiyingzimu.png",
    description: "AI字幕，翻译、配音……",
    score: 4.4,
    ratingCount: 320,
  },
  {
    catId: 10,
    category: "视频制作",
    id: 65,
    name: "万彩微影",
    url: "https://www.animiz.cn/microvideo",
    logoUrl:
      "https://a1.x914.com/alight/i/AITeach/toolsLogo/wancaiweiying.png",
    description: "真人手绘视频、翻转文字视频、文章转视频、相册视频工具……",
    score: 4.3,
    ratingCount: 360,
  },
  {
    catId: 10,
    category: "视频制作",
    id: 66,
    name: "芦笋AI提词器",
    url: "https://tcq.lusun.com",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/luhuiAI.png",
    description: "持AI写稿、隐形提词效果、支持智能跟读",
    score: 4.2,
    ratingCount: 280,
  },
  {
    catId: 10,
    category: "视频制作",
    id: 67,
    name: "万彩AI",
    url: "https://ai.kezhan365.com",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/wancaiAI.png",
    description: "高效、好用的AI写作和短视频创作平台",
    score: 4.5,
    ratingCount: 400,
  },
  {
    catId: 11,
    category: "数字人",
    id: 68,
    name: "腾讯智影",
    url: "https://zenvideo.qq.com",
    logoUrl:
      "https://a1.x914.com/alight/i/AITeach/toolsLogo/tencent-zhiying.png",
    description: "数字人、文本配音、文章转视频……",
    score: 4.4,
    ratingCount: 380,
  },
  {
    catId: 11,
    category: "数字人",
    id: 69,
    name: "来画",
    url: "https://www.laihua.com",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/laihua.png",
    description: "动画、数字人智能制作",
    score: 4.3,
    ratingCount: 350,
  },
  {
    catId: 11,
    category: "数字人",
    id: 70,
    name: "一帧秒创",
    url: "https://aigc.yizhentv.com",
    logoUrl:
      "https://a1.x914.com/alight/i/AITeach/toolsLogo/yizhenmiaochuang.png",
    description: "AI视频，数字人、AI作画……",
    score: 4.5,
    ratingCount: 400,
  },
  {
    catId: 11,
    category: "数字人",
    id: 71,
    name: "万兴播爆",
    url: "https://virbo.wondershare.cn",
    logoUrl: "https://a1.x914.com/alight/i/AITeach/toolsLogo/wanxingbobao.png",
    description: "数字人，真人营销视频",
    score: 4.2,
    ratingCount: 320,
  },
]);
