const iconLinksOne = ref([
  //1
  "https://a1.x914.com/alight/i/AITeach/rwkv-color.png",
  "https://a1.x914.com/alight/i/AITeach/spark-color.png",
  "https://a1.x914.com/alight/i/AITeach/tiangong-color.png",
  "https://a1.x914.com/alight/i/AITeach/openai.png",
  "https://a1.x914.com/alight/i/AITeach/claude-color.png",
  //6
  "https://a1.x914.com/alight/i/AITeach/anthropic.png",
  "https://a1.x914.com/alight/i/AITeach/gemini-color.png",
  "https://a1.x914.com/alight/i/AITeach/ollama.png",
  "https://a1.x914.com/alight/i/AITeach/meta-color.png",
  "https://a1.x914.com/alight/i/AITeach/deepseek-color.png",
  //11
  "https://a1.x914.com/alight/i/AITeach/midjourney.png",
  "https://a1.x914.com/alight/i/AITeach/mistral-color.png",
  "https://a1.x914.com/alight/i/AITeach/stability-color.png",
  "https://a1.x914.com/alight/i/AITeach/huggingface-color.png",
  "https://a1.x914.com/alight/i/AITeach/bytedance-color.png",
  //16
  "https://a1.x914.com/alight/i/AITeach/dalle-color.png",
  "https://a1.x914.com/alight/i/AITeach/openrouter.png",
  "https://a1.x914.com/alight/i/AITeach/copilot-color.png",
  "https://a1.x914.com/alight/i/AITeach/cohere-color.png",
  "https://a1.x914.com/alight/i/AITeach/replicate.png",
  //21
  "https://a1.x914.com/alight/i/AITeach/zhipu-color.png",
  "https://a1.x914.com/alight/i/AITeach/runway.png",
  "https://a1.x914.com/alight/i/AITeach/perplexity-color.png",
  "https://a1.x914.com/alight/i/AITeach/gemma-color.png",
  "https://a1.x914.com/alight/i/AITeach/chatglm-color.png",
  //26
  "https://a1.x914.com/alight/i/AITeach/flux.png",
  "https://a1.x914.com/alight/i/AITeach/grok.png",
  "https://a1.x914.com/alight/i/AITeach/suno.png",
  "https://a1.x914.com/alight/i/AITeach/groq.png",
  "https://a1.x914.com/alight/i/AITeach/qwen-color.png",
  //31
  "https://a1.x914.com/alight/i/AITeach/together-color.png",
  "https://a1.x914.com/alight/i/AITeach/fireworks.png",
  "https://a1.x914.com/alight/i/AITeach/kling-color.png",
  "https://a1.x914.com/alight/i/AITeach/google-color.png",
  "https://a1.x914.com/alight/i/AITeach/luma-color.png",
  //36
  "https://a1.x914.com/alight/i/AITeach/bedrock-color.png",
  "https://a1.x914.com/alight/i/AITeach/vertexai-color.png",
  "https://a1.x914.com/alight/i/AITeach/doubao-color.png",
  "https://a1.x914.com/alight/i/AITeach/adobe-color.png",
  "https://a1.x914.com/alight/i/AITeach/adobefirefly-color.png",
]);
const iconLinksTwo = ref([
  //41
  "https://a1.x914.com/alight/i/AITeach/ai21.png",
  "https://a1.x914.com/alight/i/AITeach/ai360-color.png",
  "https://a1.x914.com/alight/i/AITeach/aimass-color.png",
  "https://a1.x914.com/alight/i/AITeach/alibaba-color.png",
  "https://a1.x914.com/alight/i/AITeach/alibabacloud-color.png",
  //46
  "https://a1.x914.com/alight/i/AITeach/antgroup-color.png",
  "https://a1.x914.com/alight/i/AITeach/automatic-color.png",
  "https://a1.x914.com/alight/i/AITeach/aws-color.png",
  "https://a1.x914.com/alight/i/AITeach/aya-color.png",
  "https://a1.x914.com/alight/i/AITeach/azure-color.png",
  //51
  "https://a1.x914.com/alight/i/AITeach/baichuan-color.png",
  "https://a1.x914.com/alight/i/AITeach/baidu-color.png",
  "https://a1.x914.com/alight/i/AITeach/baiducloud-color.png",
  "https://a1.x914.com/alight/i/AITeach/bing-color.png",
  "https://a1.x914.com/alight/i/AITeach/civitai-color.png",
  //56
  "https://a1.x914.com/alight/i/AITeach/cloudflare-color.png",
  "https://a1.x914.com/alight/i/AITeach/codegeex-color.png",
  "https://a1.x914.com/alight/i/AITeach/cogvideo-color.png",
  "https://a1.x914.com/alight/i/AITeach/cogview-color.png",
  "https://a1.x914.com/alight/i/AITeach/colab-color.png",
  //61
  "https://a1.x914.com/alight/i/AITeach/comfyui-color.png",
  "https://a1.x914.com/alight/i/AITeach/coze.png",
  "https://a1.x914.com/alight/i/AITeach/cursor.png",
  "https://a1.x914.com/alight/i/AITeach/dbrx-color.png",
  "https://a1.x914.com/alight/i/AITeach/deepai.png",
  //66
  "https://a1.x914.com/alight/i/AITeach/deepmind-color.png",
  "https://a1.x914.com/alight/i/AITeach/dify-color.png",
  "https://a1.x914.com/alight/i/AITeach/fal.png",
  "https://a1.x914.com/alight/i/AITeach/fishaudio.png",
  "https://a1.x914.com/alight/i/AITeach/giteeai.png",
  //71
  "https://a1.x914.com/alight/i/AITeach/github.png",
  "https://a1.x914.com/alight/i/AITeach/githubcopilot.png",
  "https://a1.x914.com/alight/i/AITeach/hailuo-color.png",
  "https://a1.x914.com/alight/i/AITeach/higress-color.png",
  "https://a1.x914.com/alight/i/AITeach/hunyuan-color.png",
  //76
  "https://a1.x914.com/alight/i/AITeach/ideogram.png",
  "https://a1.x914.com/alight/i/AITeach/internlm-color.png",
  "https://a1.x914.com/alight/i/AITeach/kimi-color.png",
  "https://a1.x914.com/alight/i/AITeach/llava-color.png",
  "https://a1.x914.com/alight/i/AITeach/langchain-color.png",
]);
const iconLinksThree = ref([
  //61
  "https://a1.x914.com/alight/i/AITeach/comfyui-color.png",
  "https://a1.x914.com/alight/i/AITeach/coze.png",
  "https://a1.x914.com/alight/i/AITeach/cursor.png",
  "https://a1.x914.com/alight/i/AITeach/dbrx-color.png",
  "https://a1.x914.com/alight/i/AITeach/deepai.png",
  //66
  "https://a1.x914.com/alight/i/AITeach/deepmind-color.png",
  "https://a1.x914.com/alight/i/AITeach/dify-color.png",
  "https://a1.x914.com/alight/i/AITeach/fal.png",
  "https://a1.x914.com/alight/i/AITeach/fishaudio.png",
  "https://a1.x914.com/alight/i/AITeach/giteeai.png",
  //71
  "https://a1.x914.com/alight/i/AITeach/github.png",
  "https://a1.x914.com/alight/i/AITeach/githubcopilot.png",
  "https://a1.x914.com/alight/i/AITeach/hailuo-color.png",
  "https://a1.x914.com/alight/i/AITeach/higress-color.png",
  "https://a1.x914.com/alight/i/AITeach/hunyuan-color.png",
  //76
  "https://a1.x914.com/alight/i/AITeach/ideogram.png",
  "https://a1.x914.com/alight/i/AITeach/internlm-color.png",
  "https://a1.x914.com/alight/i/AITeach/kimi-color.png",
  "https://a1.x914.com/alight/i/AITeach/llava-color.png",
  "https://a1.x914.com/alight/i/AITeach/langchain-color.png",
  //81
  "https://a1.x914.com/alight/i/AITeach/langfuse-color.png",
  "https://a1.x914.com/alight/i/AITeach/livekit-color.png",
  "https://a1.x914.com/alight/i/AITeach/lmstudio.png",
  "https://a1.x914.com/alight/i/AITeach/lobehub-color.png",
  "https://a1.x914.com/alight/i/AITeach/magic.png",
  //86
  "https://a1.x914.com/alight/i/AITeach/minimax-color.png",
  "https://a1.x914.com/alight/i/AITeach/modelscope-color.png",
  "https://a1.x914.com/alight/i/AITeach/moonshot.png",
  "https://a1.x914.com/alight/i/AITeach/myshell-color.png",
  "https://a1.x914.com/alight/i/AITeach/notion.png",
  //91
  "https://a1.x914.com/alight/i/AITeach/nova-color.png",
  "https://a1.x914.com/alight/i/AITeach/novita-color.png",
  "https://a1.x914.com/alight/i/AITeach/nvidia-color.png",
  "https://a1.x914.com/alight/i/AITeach/openchat-color.png",
  "https://a1.x914.com/alight/i/AITeach/palm-color.png",
  //96
  "https://a1.x914.com/alight/i/AITeach/poe-color.png",
  "https://a1.x914.com/alight/i/AITeach/pollinations.png",
  "https://a1.x914.com/alight/i/AITeach/qingyan-color.png",
  "https://a1.x914.com/alight/i/AITeach/recraft.png",
  "https://a1.x914.com/alight/i/AITeach/replit-color.png",
]);