const selectedToolId = ref<any>({});

// 处理提交评分
const handleSubmitRating = async () => {
  await debounceStore.withSubmitLock(async () => {
    console.log("评分结果:", scoreStore.ratingDimensions);
    selectedToolId.value = JSON.parse(
      localStorage.getItem("selectedTool") as any
    );
    console.log(selectedToolId.value);
    await scoreStore.evaluationTransmission(selectedToolId.value.id);

    ElMessage({
      message: "评分提交成功，请勿重复提交！",
      type: "success",
    });
  });
};

// 使用防抖包装提交函数
const submitRating = debounceStore.debounce(handleSubmitRating, 500);

onMounted(() => {
  selectedToolId.value = JSON.parse(
    localStorage.getItem("selectedTool") as any
  );
  scoreStore.ToolsDetailGet(selectedToolId.value.id);
});